"""empty message

Revision ID: 2cc1c9fef5ad
Revises: eae2293d3132
Create Date: 2019-08-02 13:41:23.689419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc1c9fef5ad'
down_revision = 'eae2293d3132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logging')
    # ### end Alembic commands ###
