"""empty message

Revision ID: 514a4886080f
Revises: 3f0e402cb644
Create Date: 2019-10-07 11:27:14.049593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '514a4886080f'
down_revision = '3f0e402cb644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    post_status = postgresql.ENUM(
        'processing', 'published', 'archived', name='poststatus')
    post_status.create(op.get_bind())

    op.add_column('posts', sa.Column('status', sa.Enum(
        'processing', 'published', 'archived', name='poststatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###

    post_status = postgresql.ENUM(
        'processing', 'published', 'archived', name='poststatus')
    post_status.drop(op.get_bind())
