"""empty message

Revision ID: 5a5a0681decb
Revises: 74ae77549ba0
Create Date: 2019-07-25 16:46:38.221330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5a5a0681decb'
down_revision = '74ae77549ba0'
branch_labels = None
depends_on = None


def upgrade():
    task_priority = postgresql.ENUM(
        'low', 'medium', 'high', name='taskpriority')
    task_priority.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum(
        'low', 'medium', 'high', name='taskpriority'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
