"""empty message

Revision ID: 72d078418dda
Revises: f95760c8212b
Create Date: 2019-07-16 15:27:44.366833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d078418dda'
down_revision = 'f95760c8212b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('attached_file', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attached_file')
    # ### end Alembic commands ###
