"""empty message

Revision ID: d90a2797b9c1
Revises: 5a5a0681decb
Create Date: 2019-07-30 12:55:26.420259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90a2797b9c1'
down_revision = '5a5a0681decb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pinned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'pinned')
    # ### end Alembic commands ###
