"""empty message

Revision ID: e7130ccac601
Revises: 2c1a53895382
Create Date: 2019-10-21 16:22:11.870829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7130ccac601'
down_revision = '2c1a53895382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('social_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'social_accounts', ['social_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'social_account_id')
    # ### end Alembic commands ###
