"""empty message

Revision ID: eae2293d3132
Revises: d90a2797b9c1
Create Date: 2019-07-30 14:41:13.189267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae2293d3132'
down_revision = 'd90a2797b9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline')
    op.alter_column('comments', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
